# Generated by Django 3.2.9 on 2021-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
