# Generated by Django 3.2.9 on 2021-11-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211130_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
