# Generated by Django 3.2.9 on 2021-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='baseprice',
        ),
        migrations.AddField(
            model_name='order',
            name='borrowprice',
            field=models.FloatField(default=0.0),
        ),
    ]
